### ISSUE TITLE
SignIn no longer appears in Website

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/SignIn#100]
### Steps to reproduce

0. Delete the existing database
1. Start Website and WebsiteProvider (`develop` branch)
2. Start Sign In (`develop` branch)
3. Go to `http://localhost:8080/website/cms`

### Expected result

You should see a sign in icon in the top right corner.

### Actual result

You don't see a sign in icon in the top right corner.

### Technical information

This seems **not** to be connected with the recent changes in Starcounter (tested in both 2.3.0.6350 and 2.3.1.6433) changes and Website app.

The last good commit in SignIn is: 0187c3405840ab5e2152f0c9fd1bbb1b96b2b32b 
The first bad commit in SignIn is: f30145785c9f9082862ed025631c0f108df09631

### Screenshot

![2017-05-16 16_41_15-website](https://cloud.githubusercontent.com/assets/566463/26111851/947e406a-3a56-11e7-8973-59548bd379c2.png)

![2017-05-16 16_43_42-website](https://cloud.githubusercontent.com/assets/566463/26111971/e4693a30-3a56-11e7-9005-d8ee1505dd33.png)

**Comment by warpech** [comment]
@un-tone says this is fixed in https://github.com/StarcounterApps/Website/pull/70. Will review

**Comment by warpech** [comment]
I confirm that the above PR fixes the problem.

**Comment by un-tone** [comment]
Closing as done with PR https://github.com/StarcounterApps/Website/pull/70
