### ISSUE TITLE
SignIn needs an icon that is displayed in Launchpad

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/SignIn#105]
Unlike other apps (People, Images, Products), SignIn does not present at icon in the Launchpad.

The icon should point to `/signin`. That URL should be an alias of `/signin/signinuser`

Use the icon that already is in this repo: `src/SignIn/wwwroot/SignIn/css/empty_user.svg` (that is displayed in the top right corner of Launcher when SignIn is running)

**Comment by threezool** [comment]
Merged #106

**Comment by warpech** [comment]
This part was not done:

> The icon should point to `/signin`. That URL should be an alias of `/signin/signinuser`

Because of that, clicking on the Sign In icon gets you to a 404 page.

**Comment by warpech** [comment]
Since @threezool is on vacation, @bouguila can you maybe take this?

**Comment by bouguila** [comment]
@warpech i'll take care of this 👍

**Comment by bouguila** [comment]
closing as fixed.
