### ISSUE TITLE
Implement the mandatory app guidelines

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/SignIn#119]
Implementing the guidelines:

- https://github.com/Starcounter/Guidelines/blob/mandatory-features/mandatory-features.md
- https://github.com/Starcounter/Guidelines/blob/mandatory-features/required-and-sample-data.md

should fix the problems reported by @rogeralsing in https://github.com/Starcounter/Home/issues/156

**Comment by Mihaiii** [comment]
@warpech 
It would be useful for me if I could start doing this after https://github.com/StarcounterApps/Images/pull/112 is merged.
Would that be ok?

**Comment by warpech** [comment]
Let's see what's the @tomalec's answer there.

**Comment by warpech** [comment]
https://github.com/StarcounterApps/Images/pull/112 is merged now.

**Comment by Mihaiii** [comment]
The links in the first comment don't work after this commit: https://github.com/Starcounter/Guidelines/pull/40/commits/ce4d437c4a9514988bec6e5f1e95482cb108e242

Also related to https://github.com/Starcounter/Guidelines/pull/40

New link: https://github.com/Starcounter/Docs/pull/121

**Comment by Mihaiii** [comment]
Closing as done.
