### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/SignIn#134]
Please release a new version of this app that includes #127, #129.

I am setting up a demo of the Website app and I can't make it with the version 6.0.0 which is currently in the app store.

**Comment by habib535** [comment]
I would suggest not to include #129 yet because all the apps will require a new release for this change and @bouguila was going to do that a couple of days back but I stopped him because of https://github.com/Starcounter/RebelsLounge/issues/126

**Comment by habib535** [comment]
I will take this and release a new version for all the apps on inside.starcounter.com but will have to wait for the nightly build. @alemoi will trigger once he reaches office.

**Comment by warpech** [comment]
@habib535 reports this is still blocked by https://github.com/Starcounter/RebelsLounge/issues/126#issuecomment-332480804.

**Comment by habib535** [comment]
http://inside.starcounter.com/ now has the latest version of Starcounter
All the apps are now using the updated Blending API. The only app I didn't release a new version for is `AutoAuditSuite` because it doesn't have `package.bat` file.

**Comment by warpech** [comment]
Great, thanks!
