### ISSUE TITLE
Replace juicy-style with template is="starcounter-composition"

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/SignIn#36]
This task is the part of the effort to implement https://starcounter.gitbooks.io/rebelslounge/content/app/client/layouts/longterm_solution_md.html

Support for `juicy-style` is being removed from Launcher, starting from Launcher `develop` branch.

Use Products app as reference for this task (https://github.com/StarcounterSamples/Products/issues/18)

---

In the SignIn app, replace `juicy-style` with `template is="starcounter-composition"`.

Do this on SignIn `develop` branch (see [branching policy](https://starcounter.gitbooks.io/guidelines/content/branching.html))

**Comment by joozek78** [comment]
Fixed in PR #72
