### ISSUE TITLE
Problem with auto log off

### ISSUE THREAD

**Issue by aloscha** [StarcounterApps/SignIn#48]
I use SignIn app + UserAdmin app + third part application. In latest application, first I should login and there are link, which is redirect into user details (UserAdmin app) based on OntologyMapping. Sometimes redirect show details, sometimes not, after refresh I'm always logout.

I've use latest pnext from Starcounter.

**Comment by Mnosek** [comment]
cc @warpech

**Comment by warpech** [comment]
@aloscha could you please provide steps to reproduce?

**Comment by aloscha** [comment]
Just go to Dashboard of ProcessDesigner in SO project and click Assignee. Then after redirection you should refresh page and I'm log out then.
![image](https://cloud.githubusercontent.com/assets/5141943/19927687/17cc69c4-a0fb-11e6-9541-366be3e69781.png)

Also before you will build project etc., please go to `ChecklistDesigner.Helper.UriHelper` and uncomment line 54.

It's really strange but on my local pc it's works (after we uncomment), but on prod server and on @Mnosek pc doesn't.

**Comment by warpech** [comment]
Is this still reproducible?

**Comment by warpech** [comment]
Closing as not reproducible anymore
