### ISSUE TITLE
One click to auto generate admin user

### ISSUE THREAD

**Issue by andwah** [StarcounterApps/SignIn#51]
If:
* there is no user with username "admin"
* and current request originates from localhost

then:

* display a button in all "sign-in" forms
  * with label "generate admin account" (or equivalent)
  * with tooltip "This will generate a default admin account" (or equivalent)
  * which, after clicking will... generate the admin account :)

also:

  * Remember to check the conditions in input handler (the fact that a button is not visible doesn't mean a user can't trigger it)
  * Don't remove the `/signin/generateadminuser` handler, but make it return a note about this button in response (so our users can learn about it)
* Double check if "request originates from localhost" condition still works after using recommended ssl configuration (@joozek78 can help with that)

Original description
---
It would be nice to make the life easy for new users of the signin app,  a new user will probably not know about the `/signin/generateadminuser` handler.

Maybe we can add a button `create admin user` on the popup page if there is no admin user and if it's on local machine.

**Comment by andwah** [comment]
*bump* 
This starts to annoy me. and i think new users will also have a hard time to get started (they need to i guess check the source code on how to generate a default admin user). 
Before when signin app was started it auto-created an admin user if it did not exist.

I think we should make the life as easy as possible for our users to use this app.

Please think this over :-)

**Comment by mmnosek** [comment]
I agree! A new button should pop up when:
- There are no users in a DB ( I can imagine a situation when somebody doesn't want to have admin and there is some other "thing" that creates initial users for him)
- It's local machine

**Comment by joozek78** [comment]
@andwah I took the liberty of editing the description to make it more imperative. Your original request is at the bottom

**Comment by andwah** [comment]
@joozek78 Thanks.

The button/link should do the same thing that `/signin/generateadminuser` does but with a "nice" user experience and it should only be visible when it's needed

**Comment by warpech** [comment]
This PR presents a convention how to create sample data in the apps: https://github.com/Starcounter/Docs/pull/121

I think that this issue is good to implement.

**Comment by LarsTjernstrom** [comment]
My input is that we should let the user specify a password for the admin account, since it's a security issue creating default passwords for such account.

**Comment by LarsTjernstrom** [comment]
Implemented in #127
Note. The  "Create Admin account" button is only implemented in the SignInFormPage
