### ISSUE TITLE
Replace paper-icon-button with SVG icon

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/SignIn#63]
After https://github.com/StarcounterPrefabs/SignIn/pull/59 is merged, we should unify how SVG icons are used.

Right now, we display a `paper-icon-button` for a non signed in user, and a SVG icon for a signed in user.

It should be the same SVG icon in both cases.

![bug](https://cloud.githubusercontent.com/assets/566463/22285377/b2b98fde-e2eb-11e6-8435-4cfc1f99858f.gif)

**Comment by warpech** [comment]
Also `paper-button` seems to be not needed anymore.

**Comment by warpech** [comment]
@un-tone can you pls take this?

**Comment by un-tone** [comment]
Created PR https://github.com/StarcounterApps/SignIn/pull/94

**Comment by un-tone** [comment]
Closing as done.
