### ISSUE TITLE
After Signing in User have to refresh the page.

### ISSUE THREAD

**Issue by atifwaqar** [StarcounterApps/SignIn#67]
After singing in the page does not update, and user have to refresh the page to see the logged in content. I tried to sync the latest code and tested the behavior again, but its still the same.

(The last commit in sighin repo is `Merge remote-tracking branch 'refs/remotes/origin/develop`)

**Comment by warpech** [comment]
Actually it is not caused by SignIn, but by the other app that should react to people signing in. Some of our sample apps listen to it using commit hooks, for example: https://github.com/StarcounterPrefabs/UserAdmin/blob/develop/src/UserAdmin/Api/CommitHooks.cs

**Comment by atifwaqar** [comment]
@warpech we are using UserAdmin app as well, shouldn't UserAdmin app fix this automatically? or do I have to add this commithook in my project?

**Comment by warpech** [comment]
Every app needs to repeat that using commit hooks for its own view-models.

**Comment by atifwaqar** [comment]
@warpech Thanks. This was helpful.
