### ISSUE TITLE
Master branch build error with Starcounter release 2.3 nightly

### ISSUE THREAD

**Issue by KmaTTi89** [StarcounterApps/SignIn#76]
`ViewModels\SignInPage.json.cs(25, 43): error CS0618: 'Somebody.ImageURL' is obsolete: 'ImageURL is obsolete in Somebody, use Illustration instead.'
ViewModels\SignInPage.json.cs(27, 37): error CS0618: 'Somebody.ImageURL' is obsolete: 'ImageURL is obsolete in Somebody, use Illustration instead.'`

Teamcity master branch failed with sc release 2.3 nightly

**Comment by Mackiovello** [comment]
`develop` is now merged into `master`, so it should no longer be an issue. Closing.
