### ISSUE TITLE
Question : What is `Mail server` in Starcounter?

### ISSUE THREAD

**Issue by atifwaqar** [StarcounterApps/SignIn#78]
### Question
What is `Mail Server` in Starcounter? and how to configure it?
When I try to reset my password (Through Forget Password button, Handler: `/signin/signinuser`), I get the error `Mail server is currently unavailable.`

### Branch
Develop
##### Starcounter version 
2.3.0.5916

##### Involved apps' version
Launcher
UserAdmin
SignIn
 
##### Browsers affected

- [X] Chrome

### Screenshot
![image](https://cloud.githubusercontent.com/assets/4388707/24374957/f4736c9e-1336-11e7-9811-401d86d611cc.png)

**Comment by warpech** [comment]
There is no "mail server" in Starcounter. Mail server is the concept of the SignIn app, configured on the Settings page.

**Comment by warpech** [comment]
I have tried to answer using https://github.com/StarcounterApps/SignIn/pull/79/files

Anything more I should add there, @atifwaqar?

**Comment by warpech** [comment]
The question is now answered in https://github.com/StarcounterApps/SignIn/blob/develop/README.md. 

Closing as done.

**Comment by atifwaqar** [comment]
Nice detailed readme. Thanks :)
