### ISSUE TITLE
launcher-toolbar launcher-topbar is disappeared in home page 

### ISSUE THREAD

**Issue by Tajree** [StarcounterApps/SignIn#83]
### Steps to reproduce
- login with valid user id and password
- then home is visible after sucessfully logged in

### Expected result
- launcher-toolbar launcher-topbar should be statically visible in all pages

### Actual result
- launcher-toolbar launcher-topbar is disappeared in home page only: here is the link: http://224.adfenix.com/adfenix/signin. See the given screen shot:

##### Starcounter version 
latest version: 2.3
##### Browsers affected

- [ 1] Chrome
![topbar is disappeared in home page_li](https://cloud.githubusercontent.com/assets/20770654/24754495/752d161e-1af8-11e7-9f99-b79b5693ed52.jpg)

- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

**Comment by atifwaqar** [comment]
Oops, This is as expected @Tajree . Do close this issue.
