### ISSUE TITLE
Create a full-page sign-in form

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/SignIn#89]
Some (most) business systems, want to have a full page sign-in experience.

In case of @jwillmer the sign in form has not only to be full page, it even has to be wrapped in a different Website surface than other pages.

This is doable, if we add a "Display the sign-in form as a full page" (ON/OFF) that makes the `/signin/signinuser?{string OriginalUrl}` partial always redirect to its own URL.

Right now, that partial appears in line, as a sibling to the partial that represents unauthorised page in the interested app. For example see the screenshot:

![2017-04-21 12_04_31-themes running - microsoft visual studio](https://cloud.githubusercontent.com/assets/566463/25273121/b67d1748-268a-11e7-974d-3e261ae0676e.png)

If we set "Display the sign-in form as a full page" to ON, instead of the above rendering, the user will be redirected to `/signin/signinuser?{string OriginalUrl}`, which in turn can be catched by a catching rule in the Website app, resulting in a different surface.

@miyconst, @joozek78, @un-tone WDYT?

**Comment by joozek78** [comment]
I think it's a very good idea. I would even turn this on by default

**Comment by un-tone** [comment]
It's definitely a good idea. I agree with @joozek78 to turn this on by default.

**Comment by un-tone** [comment]
There are 3 PRs above for this issue.
But it works correctly only when the SignIn app starts last after the UserAdmin. Overwise the Website app handles `/useradmin/partial/unauthenticated?return_uri={?}` URI, not the `/signin/signinuser?{?}` even if I open `http://localhost:8080/signin/signinuser?%2fuseradmin%2fadmin%2fusers` on a new page. I have not found a way to resolve it.

**Comment by un-tone** [comment]
The issue from comment above is eliminated with 2.3.0.6347 (https://github.com/Starcounter/CompanyTrack/issues/292#issuecomment-296775379).
@warpech can I rely on changes from that Starcounter build and wait while it will be merged to 2.3, WDYT?

**Comment by warpech** [comment]
Any idea how the above problem is related to 2.3.0.6347? I don't see a direct reason why that build would fix the problem.

But anyway, I think that it should not block us from merging https://github.com/StarcounterApps/SignIn/pull/93, because that is not a regression. Right?

**Comment by un-tone** [comment]
It seems like the Request.Uri is beeing changed to the last called URI registered with UriMapping. I have an example.

 - Start SignIn, Website, WebsiteProvider, UserAdmin.
 - Go to the `http://localhost:8080/signin/signinuser?%2fuseradmin%2fadmin%2fusers` in the browser.
 - The request filter registered in the Website handles the request:
```
GET /signin/signinuser?%2fuseradmin%2fadmin%2fusers HTTP/1.1\r\nHost: localhost:8080\r\nConnection: keep-alive\r\nCache-Control: max-age=0\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8\r\nAccept-Encoding: gzip, deflate, sdch, br\r\nAccept-Language: ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4\r\n\r\n
```
with request.Uri equals to `/signin/signinuser?%2fuseradmin%2fadmin%2fusers`

 - The response filter handles the same request
```
GET /signin/signinuser?%2fuseradmin%2fadmin%2fusers HTTP/1.1\r\nHost: localhost:8080\r\nConnection: keep-alive\r\nCache-Control: max-age=0\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8\r\nAccept-Encoding: gzip, deflate, sdch, br\r\nAccept-Language: ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4\r\n\r\n
```
and the request.Uri already changed and equals to `/useradmin/partial/unauthenticated?return_uri=%2fuseradmin%2fadmin%2fusers`.

In this case WebsiteProvider doesn't wrap requests with a `/signin/signinuser?{?}` URI because it doesn't see such ones.

I'm not sure is such behaviour correct and expecting?

**Comment by warpech** [comment]
I can confirm:

![2017-04-27 14_16_52-website debugging - microsoft visual studio](https://cloud.githubusercontent.com/assets/566463/25482964/34473dca-2b54-11e7-9116-b9c679a63d84.png)

Me and @un-tone both checked that in 2.3.0.6350. I assume that the same problem also exists in 2.3.0.6385.

It seems that handlers visited through `UriMapping` change the `request.Uri`.

I think that `request.Uri` should always be the original (what was requested from a browser). 

@alemoi can & should this be fixed? Solving this problem is crucial for the task that we are doing here.

**Comment by alemoi** [comment]
Sorry, I didn't really get this one :)

> Me and @un-tone both checked that in 2.3.0.6350.
> @un-tone reports that this problem is gone in 2.3.0.6347. I assume this is because UriMapping/Blending.Map was rewritten. No action needed.

So the problem exists in 6350 but not in 6347? 

Regarding the `request.Uri` it can be changed between the calls. That's why there is a `Handle.IncomingRequest`, that I thought is documented, but does not seem to be the case. Does it fix the problem you experience?

**Comment by un-tone** [comment]
The problem with `request.Uri` is gone with 2.3.1.6402.

**Comment by warpech** [comment]
Status of the PRs:

- StarcounterApps/SignIn#93 - reviewed, mergable
- StarcounterApps/Simplified#51 - merged
- StarcounterApps/Website#92 - reviewed, minor comments. Follow up non-blocking issue: https://github.com/StarcounterApps/Website/issues/94

**Comment by un-tone** [comment]
I reverted the PR https://github.com/StarcounterApps/SignIn/pull/93 (with https://github.com/StarcounterApps/SignIn/pull/95). Need to be reworked.

**Comment by warpech** [comment]
@un-tone, what's the status of changes in SignIn?

**Comment by un-tone** [comment]
It seemed to be simple but I have different issues which I can't resolve without help. I have tried different approaches.

**Issue 1. `puppet-redirect` element on the MasterPage**
I use the following apps:
 * SignIn (`full-page-sign-in-form-2` branch)
 * UserAdmin (`develop` branch)
 * Website (`bugfix/unmaping` branch)

1. Run the apps
2. Go to `http://localhost:8080/useradmin`
3. Got the following error when redirecting the `http://localhost:8080/signin/signinuser?%2fuseradmin%2fadmin%2fusers`:
```
System.ArgumentOutOfRangeException: Индекс за пределами диапазона. Индекс должен быть положительным числом, а его размер не должен превышать размер коллекции.
Имя параметра: index
   в System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   в Starcounter.XSON.SiblingList.GetNamespace(Int32 siblingIndex) в C:\TeamCity\TeamCity10\buildAgent\work\sc-5384\Level1\src\Starcounter.XSON\Class Json\SiblingList.cs:строка 162
   в Starcounter.XSON.JsonPatch.WritePathRecursive(Json json, TextWriter writer, Boolean includeNamespace, Boolean calledFromStepSibling) в C:\TeamCity\TeamCity10\buildAgent\work\sc-5384\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:строка 298
   в Starcounter.XSON.JsonPatch.WritePath(Change change, TextWriter writer, Boolean includeNamespace) в C:\TeamCity\TeamCity10\buildAgent\work\sc-5384\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:строка 222
   в Starcounter.XSON.JsonPatch.WritePatch(Change change, TextWriter writer, Boolean includeNamespace) в C:\TeamCity\TeamCity10\buildAgent\work\sc-5384\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:строка 181
   в Starcounter.XSON.JsonPatch.Generate(Json json, Boolean flushLog, Boolean includeNamespace) в C:\TeamCity\TeamCity10\buildAgent\work\sc-5384\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:строка 150
   в Starcounter.Internal.JsonMimeConverter.Convert(Request request, IResource before, MimeType mimeType, MimeType& resultingMimeType) в C:\TeamCity\TeamCity10\buildAgent\work\sc-5384\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\JsonMimeConverter.cs:строка 18
   в Starcounter.Json.AsMimeType(MimeType mimeType, MimeType& resultingMimeType, Request request) в C:\TeamCity\TeamCity10\buildAgent\work\sc-5384\Level1\src\Starcounter.XSON\Class Json\Json.IResource.cs:строка 45
   в Starcounter.Response.ConstructFromFields(Request req, Byte[] givenBuffer) в C:\TeamCity\TeamCity10\buildAgent\work\sc-5384\Level1\src\Starcounter.Internal\Http\Response.cs:строка 809
   в Starcounter.Request.SendResponse(Response resp, Byte[] serializationBuf) в C:\TeamCity\TeamCity10\buildAgent\work\sc-5384\Level1\src\Starcounter.Internal\Http\Request.cs:строка 1241
   в Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) в C:\TeamCity\TeamCity10\buildAgent\work\sc-5384\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:строка 810
ParamName=index
HResult=-2146233086
```
The error can be disappeared if remove the `history` attribute from the `puppet-redirect` element. But in this case the redirecting looks ugly in a browser and there are another issues similar as described below.

If I run only SignIn and UserAdmin apps without Website blending doesn't work correctly. It doesn't show SignIn's partial:
![image](https://cloud.githubusercontent.com/assets/1625378/26399333/3c75f0cc-4085-11e7-8d97-f7b21fae0e53.png)

When I refresh the page it shows the SignIn's partial but doesn't show the UserAdmin's one:
![image](https://cloud.githubusercontent.com/assets/1625378/26399527/ec46ae7e-4085-11e7-9eca-abcfe059118d.png)
The response doesn't contain UserAdmin's data though it has been requested (I checked it debugging).

**Comment by un-tone** [comment]
**Issue 2. `/signin/partial/signinuser?{?}` handler is extracted**
I use the following apps:
 * SignIn (**`signin-form-partials`** branch, PR [SignIn#103](https://github.com/StarcounterApps/SignIn/pull/103/files?w=1))
 * UserAdmin (`develop` branch)

1. Run the apps
2. Go to `http://localhost:8080/useradmin`

Here I have similar issues with blending:
![image](https://cloud.githubusercontent.com/assets/1625378/26400293/0730f73c-4089-11e7-88a7-31b0f04ff624.png)

After refreshing all partials are appeared:
![image](https://cloud.githubusercontent.com/assets/1625378/26400330/2110bb1a-4089-11e7-955d-b0d263a8c460.png)

After all I can't find any well-working approach. I suppose there are some deeper issues

**Comment by un-tone** [comment]
For some reason the described issue from https://github.com/StarcounterApps/SignIn/issues/89#issuecomment-303687808 was gone (and was appeared another one but I fixed it) and it all works well now.
I create PR https://github.com/StarcounterApps/SignIn/issues/89#issuecomment-303687808, please review.

**Comment by un-tone** [comment]
Closing as done
