### ISSUE TITLE
Mention of SignIn in apps that require a signed in user

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/SignIn#91]
Some of our sample apps have a check for a signed in user. `README.md` files should have a consistent message that a signed in system user is needed for the app to work. Sign In app is the app that has the interface to sign in a user as well as the tool to create the default admin user.

In my opinion there should be not more than 2 sentences in `README.md` of each app that needs it, with a link to more info in SignIn's `README.md`. 

We should not make it look as if Sign In is the **only** app that can sign in a user. It is just "a" app that can do it.

@Mackiovello could you propose the text change to the following files?

- https://github.com/StarcounterApps/SignIn/blob/develop/README.md
- https://github.com/StarcounterApps/People/blob/develop/README.md
- https://github.com/StarcounterApps/UserAdmin/blob/develop/README.md
- https://github.com/StarcounterApps/Website/blob/develop/README.md

**Comment by Mackiovello** [comment]
All the apps now have updated readme instructions. Closing
